[package]
name = "raytracer"
version = "0.1.0"
authors = ["Lucas <lucas.tabis@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
image = "0.23.3"
num = "0.2.1"